# Generated by Django 5.0.2 on 2024-03-01 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.drink'),
        ),
        migrations.AddField(
            model_name='drinkingredient',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.drink'),
        ),
        migrations.AddField(
            model_name='drinkingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ingredient'),
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(through='product.DrinkIngredient', to='product.ingredient'),
        ),
    ]
